### ISSUE TITLE
Off-topic but somewhat related

### ISSUE THREAD

**Issue by cesss** [andrewwillmott/arg-spec#1]
I didn't see contact info in your profile, so I'm opening this issue here. My question is actually about your radiosity code at CMU, although as I said it's not 100% off-topic here because this arg-spec project looks as a new generation of the ArgParse code you used in the radiosity code...

I'm trying to compile your experimental radiator version (the one called "reactor" that has the face cluster hierarchy implementation). Yes, I know, it's old code, but I'm almost there (I built gcl-all, and rad). But now, when building radvis, the xforms sources are autogenerated from the .fd files with a Perl script, and I'm getting an almost empty header, that then fails to compile (it has an unmatched closing brace, and the header is almost empty). So, I'm guessing that maybe you were using an old Perl version for the scripts that generate the sources... do you remember the Perl version you used?

BTW, I checked that the standard radiator code (the one without face cluster hierarchy) doesn't autogenerate the sources, so maybe it doesn't have this problem, but I didn't try to build it yet... I'm starting with the experimental code first.

If you remember the Perl version, tell me, and I'll try to run the scripts with that version. Do you remember if it was Perl 5.x or 4.x?

Thanks!!

**Comment by cesss** [comment]
If you happen to have a copy of the autogenerated (by Perl) files in the radvis directory, I think it would suffice, as I don’t think I’ll need to modify the fd forms files in the future, I just need to build radvis.

**Comment by cesss** [comment]
I was able to fix it. The key was to substitute all occurrences of "split;" by "@_ = split;" in the perl script, in order to workaround a deprecated perl syntax.

**Comment by andrewwillmott** [comment]
Apologies -- for some reason I'm not getting notification emails for new issues, and GitHub doesn't surface them on the overview page. I only found this after manually searching for all open issues after someone at work notified me about another issue I'd not responded to.

This is indeed *very* old code! So I'm not surprised you had build issues. I suspect the perl version was pre-4 even :). I'm glad you found a fix.

I occasionally think about dusting this stuff off and replacing the UI with something like ImGui, but finite element methods seem a lot less useful these days (monte carlo methods scale so much better), so the priority's been pretty low.

ArgSpec is indeed code I've carried around and improved over the years, I seem to wind up doing a lot of command-line and data scripting stuff which it's useful for.

**Comment by cesss** [comment]
Thanks! Yes, I'm precisely in the process of implementing "classic radiosity" algorithms, and my draft considers a GUI-agnostic approach (GUI backend-based, with ImGui as one of the GUIs I'd like to target in the first version). Regarding your code, it's not obvious to determine what's implemented or not... for example, hierarchical and wavelet algorithms are disabled by default in your latest experimental version of the code (the one with face clusters), and I don't really know if it was for saving build time, or because their implementation was not finished. When I enable them and rebuild, I tend to get crashes, although maybe the reason is that I'm not tweaking the algorithms parameters right.
